version: '3.8'

services:
  qrimage:
    build: .
    container_name: qrimage
    restart: unless-stopped
    ports:
      - "3020:80"
    environment:
      - VITE_SUPABASE_URL=http://82.25.69.57:8129
      - VITE_SUPABASE_ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoiYW5vbiIsImlzcyI6InN1cGFiYXNlLWluc3RhbmNlLW1hbmFnZXIiLCJpYXQiOjE3NTM0NTc5OTUsImV4cCI6MTc4NDk5Mzk5NX0.37ZRuTt8muYWPDaS-xsjje3js2sGApOkjVxpg68pjeY
      - VITE_SUPABASE_SERVICE_ROLE_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoic2VydmljZV9yb2xlIiwiaXNzIjoic3VwYWJhc2UtaW5zdGFuY2UtbWFuYWdlciIsImlhdCI6MTc1MzQ1Nzk5NSwiZXhwIjoxNzg0OTkzOTk1fQ.bGkXZFmvvQRYbkot4iY12aBofCjQqM3M6cAJ6lMWZlYk0owy_1abtLD_C1VXczVJXV1xLEiTHvvA4
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      timeout: 10s
      interval: 30s
      retries: 3
      start_period: 40s
    labels:
      - "traefik.enable=false"
      - "app=qrimage"
      - "environment=production"