// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://icrlmjuuqciypurkvdrp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImljcmxtanV1cWNpeXB1cmt2ZHJwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIyNzMyMjMsImV4cCI6MjA2Nzg0OTIyM30.tPteTAWFti5gJrJZGiPjcM_YZ8UJacCH997MaApz1_8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});